#spring.application.name=foodcatalogue

spring:
  application:
    name: FOOD-CATALOGUE
  profiles:
    active:
      - local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9093

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true